name: Update CV

on:
  workflow_dispatch:
    inputs:
      sha:
        description: "CV commit SHA"
        required: false

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
        with:
          token: ${{ secrets.GH_COMMIT_TOKEN }}

      - name: Install Nix
        uses: nixbuild/nix-quick-install-action@v35

      - name: Bump cv flake input
        run: nix flake lock --update-input cv

      - name: Commit lockfile
        uses: stefanzweifel/git-auto-commit-action@v7
        with:
          commit_message: "chore: bump cv to ${{ github.event.inputs.sha }}"
